# Generated by Django 5.1.4 on 2025-01-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommApp', '0014_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
