# Generated by Django 5.1.4 on 2025-01-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommApp', '0015_remove_blogpost_image_url_remove_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=0, upload_to='upload'),
        ),
    ]
