# Generated by Django 5.1.4 on 2025-01-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommApp', '0016_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=0, upload_to='upload2'),
        ),
    ]
